Update: This PR provides necessary updates to our build environment in order to build eBPF for arm64/aarch64 processors.

diff --git a/Dockerfile.arm64 b/Dockerfile.arm64
--- a/Dockerfile.arm64
+++ b/Dockerfile.arm64
@@ -1,16 +1,18 @@
-FROM alpine:3.11 as qemu
+FROM calico/bpftool:v5.0-arm64 as bpftool
+
+FROM debian:buster as qemu
+MAINTAINER Reza Ramezanpour <reza@projectcalico.org>
 
 ARG QEMU_VERSION=4.2.0-6
 ARG QEMU_ARCHS="aarch64"
 
-RUN apk --update add curl
+RUN apt update && apt install -y curl
 
 # Enable non-native runs on amd64 architecture hosts
 RUN for i in ${QEMU_ARCHS}; do curl -L https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-${i}-static.tar.gz | tar zxvf - -C /usr/bin; done
 RUN chmod +x /usr/bin/qemu-*
 
-FROM arm64v8/golang:1.15.2-alpine3.12
-MAINTAINER Trevor Tao <trevor.tao@arm.com>
+FROM arm64v8/golang:1.15.2-buster
 
 ARG MANIFEST_TOOL_VERSION=v1.0.2
 
@@ -18,7 +20,6 @@ ARG MANIFEST_TOOL_VERSION=v1.0.2
 # This must be the first RUN command in this file!
 COPY --from=qemu /usr/bin/qemu-*-static /usr/bin/
 
-# Install su-exec for use in the entrypoint.sh (so processes run as the right user)
 # Install bash for the entry script (and because it's generally useful)
 # Install curl to download glide
 # Install git for fetching Go dependencies
@@ -28,47 +29,72 @@ COPY --from=qemu /usr/bin/qemu-*-static /usr/bin/
 # Install make for building things
 # Install util-linux for column command (used for output formatting).
 # Install grep, sed, zip, and jq for use in some Makefiles (e.g. pulling versions out of glide.yaml)
-# Install shadow for useradd (it allows to use big UID)
-RUN apk update && apk add --no-cache su-exec curl bash git openssh mercurial make wget util-linux tini file grep sed jq zip shadow libpcap-dev
-RUN apk upgrade --no-cache
+# Install gcc for cgo.
+# Install clang, libbpf and newer kernel headers for building BPF binaries.
+RUN echo 'APT::Default-Release "stable";' > /etc/apt/apt.conf.d/99defaultrelease && \
+    echo 'deb     http://ftp.am.debian.org/debian/    buster-backports main contrib non-free' > /etc/apt/sources.list.d/buster-backports.list && \
+    apt-get -y update &&  \
+    apt-get -y upgrade && \
+    apt-get install --no-install-recommends -y -t buster-backports \
+        libbpf-dev linux-headers-arm64 && \
+    apt-get install --no-install-recommends -y \
+        curl bash git openssh-client mercurial make wget util-linux file grep sed jq zip \
+        llvm-11 clang-11 binutils file iproute2 \
+        ca-certificates gcc libc-dev bsdmainutils strace libpcap-dev && \ 
+    rm -rf /var/lib/apt/lists/*
+    
+
+# su-exec is used by the entrypoint script to execute the user's command with the right UID/GID.
+# (sudo doesn't work easily in a container.)  The version was current master at the time of writing.
+ARG SU_EXEC_VER=212b75144bbc06722fbd7661f651390dc47a43d1
+RUN  set -ex; \
+     curl -o /sbin/su-exec.c https://raw.githubusercontent.com/ncopa/su-exec/${SU_EXEC_VER}/su-exec.c; \
+     gcc -Wall /sbin/su-exec.c -o/sbin/su-exec; \
+     chown root:root /sbin/su-exec; \
+     chmod 0755 /sbin/su-exec; \
+     rm /sbin/su-exec.c
+
+# Install fossa for foss license checks
+ARG FOSSA_VER=1.1.3
+RUN curl -L https://github.com/fossas/fossa-cli/releases/download/v${FOSSA_VER}/fossa-cli_${FOSSA_VER}_linux_arm64.tar.gz | tar zxvf - -C /usr/local/bin --extract fossa
+RUN chmod +x /usr/local/bin/fossa
+
+ARG MOCKERY_VER=2.3.0
+RUN curl -L https://github.com/vektra/mockery/releases/download/v${MOCKERY_VER}/mockery_${MOCKERY_VER}_Linux_x86_64.tar.gz | tar zxvf - -C /usr/local/bin --extract mockery
+RUN chmod +x /usr/local/bin/mockery
 
 # Disable ssh host key checking
 RUN echo 'Host *' >> /etc/ssh/ssh_config \
   && echo '    StrictHostKeyChecking no' >> /etc/ssh/ssh_config
 
-# Disable cgo so that binaries we build will be fully static.
+# We want to be able to do both cgo and non-cgo builds.  That's awkward because toggling cgo
+# results in parts of the stdlib getting rebuilt (which fails due to the container's read-only
+# filesystem).  As a workaround: take a copy of the go root for cgo builds and have the
+# entrypoint script swap it into the path if it detects CGO_ENABLED=1.
+ENV GOROOT=/usr/local/go
+ENV GOCGO=/usr/local/go-cgo
+
+# Disable cgo by default so that binaries we build will be fully static by default.
 ENV CGO_ENABLED=0
 
-# Recompile the standard library with cgo disabled.  This prevents the standard library from being
-# marked stale, causing full rebuilds every time.
-RUN go install -v std
+RUN cp -a $GOROOT $GOCGO && \
+  go install -v std && \
+  rm -rf /go/src/* /root/.cache
 
-# Install glide
-RUN go get github.com/Masterminds/glide
+# Install go programs that we rely on
 ENV GLIDE_HOME /home/user/.glide
-
-# Install ginkgo CLI tool for running tests
-RUN go get github.com/onsi/ginkgo/ginkgo
-
-# Install linting tools.
-RUN go get -u gopkg.in/alecthomas/gometalinter.v2
-RUN ln -s `which gometalinter.v2` /usr/local/bin/gometalinter
-RUN gometalinter --install
-
-# Install license checking tool.
-RUN go get github.com/pmezard/licenses
-
-# Install tool to merge coverage reports.
-RUN go get github.com/wadey/gocovmerge
-
-# Install CLI tool for working with yaml files
-RUN GO111MODULE=on go get github.com/mikefarah/yq/v3
-
-# Delete all the Go sources that were downloaded, we only rely on the binaries
-RUN rm -rf /go/src/*
-
-# Install vgo (should be removed once we take Go 1.11)
-RUN go get -u golang.org/x/vgo
+RUN go get github.com/Masterminds/glide && \
+  go get github.com/onsi/ginkgo/ginkgo && \
+  go get golang.org/x/tools/cmd/goimports && \
+  wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.27.0 && \
+  golangci-lint --version && \
+  go get github.com/pmezard/licenses && \
+  go get github.com/wadey/gocovmerge && \
+  GO111MODULE=on go get github.com/mikefarah/yq/v3 && \
+  go get -u golang.org/x/vgo && \
+  go get -u github.com/jstemmer/go-junit-report && \
+  go get -u golang.org/x/tools/cmd/stringer && \
+  rm -rf /go/src/* /root/.cache
 
 # Ensure that everything under the GOPATH is writable by everyone
 RUN chmod -R 777 $GOPATH
@@ -77,5 +103,14 @@ RUN curl -sSL https://github.com/estesp/manifest-tool/releases/download/${MANIFE
     chmod +x manifest-tool && \
     mv manifest-tool /usr/bin/
 
+# crane is needed for our release targets to copy images from the dev registries to the release registries.
+RUN wget https://github.com/google/go-containerregistry/releases/download/v0.4.1/go-containerregistry_Linux_arm64.tar.gz && \
+    tar -xvf go-containerregistry_Linux_arm64.tar.gz && \
+    chmod +x crane && \
+    mv crane /usr/bin
+
+# Add bpftool for Felix UT/FV.
+COPY --from=bpftool /bpftool /usr/bin
+
 COPY entrypoint.sh /usr/local/bin/entrypoint.sh
-ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/entrypoint.sh"]
+ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
